// tslint:disable
/**
 * shiprocket
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { InlineObject } from '../models';
// @ts-ignore
import { InlineResponse200 } from '../models';
// @ts-ignore
import { InlineResponse403 } from '../models';
/**
 * AuthenticationAPIApi - axios parameter creator
 * @export
 */
export const AuthenticationAPIApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Generate Token
         * @param {InlineObject} [inlineObject] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ExternalAuthLoginPost: async (inlineObject?: InlineObject, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/external/auth/login`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof inlineObject !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(inlineObject !== undefined ? inlineObject : {}) : (inlineObject || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * [https://apiv2.shiprocket.in/v1/external/auth/logout](https://apiv2.shiprocket.in/v1/external/auth/logout)
         * @summary Token Logout
         * @param {string} contentType 
         * @param {string} authorization 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ExternalAuthLogoutPost: async (contentType: string, authorization: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'contentType' is not null or undefined
            if (contentType === null || contentType === undefined) {
                throw new RequiredError('contentType','Required parameter contentType was null or undefined when calling v1ExternalAuthLogoutPost.');
            }
            // verify required parameter 'authorization' is not null or undefined
            if (authorization === null || authorization === undefined) {
                throw new RequiredError('authorization','Required parameter authorization was null or undefined when calling v1ExternalAuthLogoutPost.');
            }
            const localVarPath = `/v1/external/auth/logout`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (contentType !== undefined && contentType !== null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthenticationAPIApi - functional programming interface
 * @export
 */
export const AuthenticationAPIApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Generate Token
         * @param {InlineObject} [inlineObject] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1ExternalAuthLoginPost(inlineObject?: InlineObject, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse200>> {
            const localVarAxiosArgs = await AuthenticationAPIApiAxiosParamCreator(configuration).v1ExternalAuthLoginPost(inlineObject, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * [https://apiv2.shiprocket.in/v1/external/auth/logout](https://apiv2.shiprocket.in/v1/external/auth/logout)
         * @summary Token Logout
         * @param {string} contentType 
         * @param {string} authorization 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1ExternalAuthLogoutPost(contentType: string, authorization: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await AuthenticationAPIApiAxiosParamCreator(configuration).v1ExternalAuthLogoutPost(contentType, authorization, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * AuthenticationAPIApi - factory interface
 * @export
 */
export const AuthenticationAPIApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Generate Token
         * @param {InlineObject} [inlineObject] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ExternalAuthLoginPost(inlineObject?: InlineObject, options?: any): AxiosPromise<InlineResponse200> {
            return AuthenticationAPIApiFp(configuration).v1ExternalAuthLoginPost(inlineObject, options).then((request) => request(axios, basePath));
        },
        /**
         * [https://apiv2.shiprocket.in/v1/external/auth/logout](https://apiv2.shiprocket.in/v1/external/auth/logout)
         * @summary Token Logout
         * @param {string} contentType 
         * @param {string} authorization 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ExternalAuthLogoutPost(contentType: string, authorization: string, options?: any): AxiosPromise<object> {
            return AuthenticationAPIApiFp(configuration).v1ExternalAuthLogoutPost(contentType, authorization, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthenticationAPIApi - interface
 * @export
 * @interface AuthenticationAPIApi
 */
export interface AuthenticationAPIApiInterface {
    /**
     * 
     * @summary Generate Token
     * @param {InlineObject} [inlineObject] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationAPIApiInterface
     */
    v1ExternalAuthLoginPost(inlineObject?: InlineObject, options?: any): AxiosPromise<InlineResponse200>;

    /**
     * [https://apiv2.shiprocket.in/v1/external/auth/logout](https://apiv2.shiprocket.in/v1/external/auth/logout)
     * @summary Token Logout
     * @param {string} contentType 
     * @param {string} authorization 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationAPIApiInterface
     */
    v1ExternalAuthLogoutPost(contentType: string, authorization: string, options?: any): AxiosPromise<object>;

}

/**
 * AuthenticationAPIApi - object-oriented interface
 * @export
 * @class AuthenticationAPIApi
 * @extends {BaseAPI}
 */
export class AuthenticationAPIApi extends BaseAPI implements AuthenticationAPIApiInterface {
    /**
     * 
     * @summary Generate Token
     * @param {InlineObject} [inlineObject] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationAPIApi
     */
    public v1ExternalAuthLoginPost(inlineObject?: InlineObject, options?: any) {
        return AuthenticationAPIApiFp(this.configuration).v1ExternalAuthLoginPost(inlineObject, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * [https://apiv2.shiprocket.in/v1/external/auth/logout](https://apiv2.shiprocket.in/v1/external/auth/logout)
     * @summary Token Logout
     * @param {string} contentType 
     * @param {string} authorization 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationAPIApi
     */
    public v1ExternalAuthLogoutPost(contentType: string, authorization: string, options?: any) {
        return AuthenticationAPIApiFp(this.configuration).v1ExternalAuthLogoutPost(contentType, authorization, options).then((request) => request(this.axios, this.basePath));
    }

}
