// tslint:disable
/**
 * shiprocket
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { InlineResponse2008 } from '../models';
/**
 * CouriersApi - axios parameter creator
 * @export
 */
export const CouriersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Use this API to check the list of couriers and the related information with Shiprocket based on the search criteria.   **Note:**  *   This API will work on a company level. *   You can use filters to sort your data. By default, all the couriers are shown if no filter is used. *   total_courier_count will change based on the filter used.       #### Parameters:  | **PARAMS** | **REQUIRED** | **DATA TYPE** | **DESCRIPTION** | **EXAMPLE** | | --- | --- | --- | --- | --- | | `type` | NO | *string* | Use this as a parameter. Possible values are : active/inactive/all | [https://apiv2.shiprocket.in/v1/external/courier/courierListWithCounts?type=active](https://apiv2.shiprocket.in/v1/external/courier/courierListWithCounts?type=active\') |
         * @summary List of Couriers
         * @param {string} contentType 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ExternalCourierCourierListWithCountsGet: async (contentType: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'contentType' is not null or undefined
            if (contentType === null || contentType === undefined) {
                throw new RequiredError('contentType','Required parameter contentType was null or undefined when calling v1ExternalCourierCourierListWithCountsGet.');
            }
            const localVarPath = `/v1/external/courier/courierListWithCounts`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (contentType !== undefined && contentType !== null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CouriersApi - functional programming interface
 * @export
 */
export const CouriersApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Use this API to check the list of couriers and the related information with Shiprocket based on the search criteria.   **Note:**  *   This API will work on a company level. *   You can use filters to sort your data. By default, all the couriers are shown if no filter is used. *   total_courier_count will change based on the filter used.       #### Parameters:  | **PARAMS** | **REQUIRED** | **DATA TYPE** | **DESCRIPTION** | **EXAMPLE** | | --- | --- | --- | --- | --- | | `type` | NO | *string* | Use this as a parameter. Possible values are : active/inactive/all | [https://apiv2.shiprocket.in/v1/external/courier/courierListWithCounts?type=active](https://apiv2.shiprocket.in/v1/external/courier/courierListWithCounts?type=active\') |
         * @summary List of Couriers
         * @param {string} contentType 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1ExternalCourierCourierListWithCountsGet(contentType: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2008>> {
            const localVarAxiosArgs = await CouriersApiAxiosParamCreator(configuration).v1ExternalCourierCourierListWithCountsGet(contentType, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * CouriersApi - factory interface
 * @export
 */
export const CouriersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Use this API to check the list of couriers and the related information with Shiprocket based on the search criteria.   **Note:**  *   This API will work on a company level. *   You can use filters to sort your data. By default, all the couriers are shown if no filter is used. *   total_courier_count will change based on the filter used.       #### Parameters:  | **PARAMS** | **REQUIRED** | **DATA TYPE** | **DESCRIPTION** | **EXAMPLE** | | --- | --- | --- | --- | --- | | `type` | NO | *string* | Use this as a parameter. Possible values are : active/inactive/all | [https://apiv2.shiprocket.in/v1/external/courier/courierListWithCounts?type=active](https://apiv2.shiprocket.in/v1/external/courier/courierListWithCounts?type=active\') |
         * @summary List of Couriers
         * @param {string} contentType 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ExternalCourierCourierListWithCountsGet(contentType: string, options?: any): AxiosPromise<InlineResponse2008> {
            return CouriersApiFp(configuration).v1ExternalCourierCourierListWithCountsGet(contentType, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CouriersApi - interface
 * @export
 * @interface CouriersApi
 */
export interface CouriersApiInterface {
    /**
     * Use this API to check the list of couriers and the related information with Shiprocket based on the search criteria.   **Note:**  *   This API will work on a company level. *   You can use filters to sort your data. By default, all the couriers are shown if no filter is used. *   total_courier_count will change based on the filter used.       #### Parameters:  | **PARAMS** | **REQUIRED** | **DATA TYPE** | **DESCRIPTION** | **EXAMPLE** | | --- | --- | --- | --- | --- | | `type` | NO | *string* | Use this as a parameter. Possible values are : active/inactive/all | [https://apiv2.shiprocket.in/v1/external/courier/courierListWithCounts?type=active](https://apiv2.shiprocket.in/v1/external/courier/courierListWithCounts?type=active\') |
     * @summary List of Couriers
     * @param {string} contentType 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CouriersApiInterface
     */
    v1ExternalCourierCourierListWithCountsGet(contentType: string, options?: any): AxiosPromise<InlineResponse2008>;

}

/**
 * CouriersApi - object-oriented interface
 * @export
 * @class CouriersApi
 * @extends {BaseAPI}
 */
export class CouriersApi extends BaseAPI implements CouriersApiInterface {
    /**
     * Use this API to check the list of couriers and the related information with Shiprocket based on the search criteria.   **Note:**  *   This API will work on a company level. *   You can use filters to sort your data. By default, all the couriers are shown if no filter is used. *   total_courier_count will change based on the filter used.       #### Parameters:  | **PARAMS** | **REQUIRED** | **DATA TYPE** | **DESCRIPTION** | **EXAMPLE** | | --- | --- | --- | --- | --- | | `type` | NO | *string* | Use this as a parameter. Possible values are : active/inactive/all | [https://apiv2.shiprocket.in/v1/external/courier/courierListWithCounts?type=active](https://apiv2.shiprocket.in/v1/external/courier/courierListWithCounts?type=active\') |
     * @summary List of Couriers
     * @param {string} contentType 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CouriersApi
     */
    public v1ExternalCourierCourierListWithCountsGet(contentType: string, options?: any) {
        return CouriersApiFp(this.configuration).v1ExternalCourierCourierListWithCountsGet(contentType, options).then((request) => request(this.axios, this.basePath));
    }

}
