// tslint:disable
/**
 * shiprocket
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { InlineResponse20025 } from '../models';
// @ts-ignore
import { InlineResponse403 } from '../models';
/**
 * HyperlocalTrackingApi - axios parameter creator
 * @export
 */
export const HyperlocalTrackingApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get the tracking details of multiple shipments by entering their AWB codes together as an array.  The response is displayed in JSON format.  **Notes:** - Data must be passed as a string array. - Maximum of 50 AWB codes is supported at a time.  #### Parameters:  | **PARAMS**  | **REQUIRED**  | **DATA TYPE**  | **DESCRIPTION**                                              | **EXAMPLE**                      | |:----------: |-------------- |--------------- |------------------------------------------------------------- |--------------------------------- | |   `awbs`    | YES           | *string*       | The AWB codes of the shipments. Must be passed as an array.  | [\"788830567028\",\"788829354408\"]  |
         * @summary Get Tracking Data for Multiple AWBS
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ExternalCourierTrackAwbsPost: async (body?: string, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/external/courier/track/awbs`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }


    
            localVarHeaderParameter['Content-Type'] = 'text/plain';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HyperlocalTrackingApi - functional programming interface
 * @export
 */
export const HyperlocalTrackingApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Get the tracking details of multiple shipments by entering their AWB codes together as an array.  The response is displayed in JSON format.  **Notes:** - Data must be passed as a string array. - Maximum of 50 AWB codes is supported at a time.  #### Parameters:  | **PARAMS**  | **REQUIRED**  | **DATA TYPE**  | **DESCRIPTION**                                              | **EXAMPLE**                      | |:----------: |-------------- |--------------- |------------------------------------------------------------- |--------------------------------- | |   `awbs`    | YES           | *string*       | The AWB codes of the shipments. Must be passed as an array.  | [\"788830567028\",\"788829354408\"]  |
         * @summary Get Tracking Data for Multiple AWBS
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1ExternalCourierTrackAwbsPost(body?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse20025>> {
            const localVarAxiosArgs = await HyperlocalTrackingApiAxiosParamCreator(configuration).v1ExternalCourierTrackAwbsPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * HyperlocalTrackingApi - factory interface
 * @export
 */
export const HyperlocalTrackingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Get the tracking details of multiple shipments by entering their AWB codes together as an array.  The response is displayed in JSON format.  **Notes:** - Data must be passed as a string array. - Maximum of 50 AWB codes is supported at a time.  #### Parameters:  | **PARAMS**  | **REQUIRED**  | **DATA TYPE**  | **DESCRIPTION**                                              | **EXAMPLE**                      | |:----------: |-------------- |--------------- |------------------------------------------------------------- |--------------------------------- | |   `awbs`    | YES           | *string*       | The AWB codes of the shipments. Must be passed as an array.  | [\"788830567028\",\"788829354408\"]  |
         * @summary Get Tracking Data for Multiple AWBS
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ExternalCourierTrackAwbsPost(body?: string, options?: any): AxiosPromise<InlineResponse20025> {
            return HyperlocalTrackingApiFp(configuration).v1ExternalCourierTrackAwbsPost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HyperlocalTrackingApi - interface
 * @export
 * @interface HyperlocalTrackingApi
 */
export interface HyperlocalTrackingApiInterface {
    /**
     * Get the tracking details of multiple shipments by entering their AWB codes together as an array.  The response is displayed in JSON format.  **Notes:** - Data must be passed as a string array. - Maximum of 50 AWB codes is supported at a time.  #### Parameters:  | **PARAMS**  | **REQUIRED**  | **DATA TYPE**  | **DESCRIPTION**                                              | **EXAMPLE**                      | |:----------: |-------------- |--------------- |------------------------------------------------------------- |--------------------------------- | |   `awbs`    | YES           | *string*       | The AWB codes of the shipments. Must be passed as an array.  | [\"788830567028\",\"788829354408\"]  |
     * @summary Get Tracking Data for Multiple AWBS
     * @param {string} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HyperlocalTrackingApiInterface
     */
    v1ExternalCourierTrackAwbsPost(body?: string, options?: any): AxiosPromise<InlineResponse20025>;

}

/**
 * HyperlocalTrackingApi - object-oriented interface
 * @export
 * @class HyperlocalTrackingApi
 * @extends {BaseAPI}
 */
export class HyperlocalTrackingApi extends BaseAPI implements HyperlocalTrackingApiInterface {
    /**
     * Get the tracking details of multiple shipments by entering their AWB codes together as an array.  The response is displayed in JSON format.  **Notes:** - Data must be passed as a string array. - Maximum of 50 AWB codes is supported at a time.  #### Parameters:  | **PARAMS**  | **REQUIRED**  | **DATA TYPE**  | **DESCRIPTION**                                              | **EXAMPLE**                      | |:----------: |-------------- |--------------- |------------------------------------------------------------- |--------------------------------- | |   `awbs`    | YES           | *string*       | The AWB codes of the shipments. Must be passed as an array.  | [\"788830567028\",\"788829354408\"]  |
     * @summary Get Tracking Data for Multiple AWBS
     * @param {string} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HyperlocalTrackingApi
     */
    public v1ExternalCourierTrackAwbsPost(body?: string, options?: any) {
        return HyperlocalTrackingApiFp(this.configuration).v1ExternalCourierTrackAwbsPost(body, options).then((request) => request(this.axios, this.basePath));
    }

}
