// tslint:disable
/**
 * shiprocket
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { InlineResponse20017 } from '../models';
// @ts-ignore
import { InlineResponse2003 } from '../models';
// @ts-ignore
import { InlineResponse403 } from '../models';
/**
 * ShipmentsApi - axios parameter creator
 * @export
 */
export const ShipmentsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Use this API to cancel a created shipment before the \"Out for Pickup\" state. Multiple AWBs can be passed together as an array to cancel them simultaneously.  **Limit: 2000 AWBs**  #### Parameters:  | **PARAMS** | **REQUIRED** | **DATA TYPE** | **DESCRIPTION** | **EXAMPLE** | | --- | --- | --- | --- | --- | | `awbs` | YES | *string* | The AWB/List of AWBs that need to be canceled. | 19041211125783 |
         * @summary Cancel a Shipment
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ExternalOrdersCancelShipmentAwbsPost: async (body?: string, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/external/orders/cancel/shipment/awbs`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }


    
            localVarHeaderParameter['Content-Type'] = 'text/plain';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get the details of a specific Shipment by passing the value of shipment_id in the endpoint URL. No other body parameters are required.  #### Path:  |          **EXAMPLE**          | |:----------------------------: | |  https://apiv2.shiprocket.in/v1/external/shipments/16016920  |
         * @summary Get Details of Specific Shipment
         * @param {string} contentType 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ExternalShipmentsGet: async (contentType: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'contentType' is not null or undefined
            if (contentType === null || contentType === undefined) {
                throw new RequiredError('contentType','Required parameter contentType was null or undefined when calling v1ExternalShipmentsGet.');
            }
            const localVarPath = `/v1/external/shipments`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (contentType !== undefined && contentType !== null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ShipmentsApi - functional programming interface
 * @export
 */
export const ShipmentsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Use this API to cancel a created shipment before the \"Out for Pickup\" state. Multiple AWBs can be passed together as an array to cancel them simultaneously.  **Limit: 2000 AWBs**  #### Parameters:  | **PARAMS** | **REQUIRED** | **DATA TYPE** | **DESCRIPTION** | **EXAMPLE** | | --- | --- | --- | --- | --- | | `awbs` | YES | *string* | The AWB/List of AWBs that need to be canceled. | 19041211125783 |
         * @summary Cancel a Shipment
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1ExternalOrdersCancelShipmentAwbsPost(body?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2003>> {
            const localVarAxiosArgs = await ShipmentsApiAxiosParamCreator(configuration).v1ExternalOrdersCancelShipmentAwbsPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get the details of a specific Shipment by passing the value of shipment_id in the endpoint URL. No other body parameters are required.  #### Path:  |          **EXAMPLE**          | |:----------------------------: | |  https://apiv2.shiprocket.in/v1/external/shipments/16016920  |
         * @summary Get Details of Specific Shipment
         * @param {string} contentType 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1ExternalShipmentsGet(contentType: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse20017>> {
            const localVarAxiosArgs = await ShipmentsApiAxiosParamCreator(configuration).v1ExternalShipmentsGet(contentType, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ShipmentsApi - factory interface
 * @export
 */
export const ShipmentsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Use this API to cancel a created shipment before the \"Out for Pickup\" state. Multiple AWBs can be passed together as an array to cancel them simultaneously.  **Limit: 2000 AWBs**  #### Parameters:  | **PARAMS** | **REQUIRED** | **DATA TYPE** | **DESCRIPTION** | **EXAMPLE** | | --- | --- | --- | --- | --- | | `awbs` | YES | *string* | The AWB/List of AWBs that need to be canceled. | 19041211125783 |
         * @summary Cancel a Shipment
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ExternalOrdersCancelShipmentAwbsPost(body?: string, options?: any): AxiosPromise<InlineResponse2003> {
            return ShipmentsApiFp(configuration).v1ExternalOrdersCancelShipmentAwbsPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Get the details of a specific Shipment by passing the value of shipment_id in the endpoint URL. No other body parameters are required.  #### Path:  |          **EXAMPLE**          | |:----------------------------: | |  https://apiv2.shiprocket.in/v1/external/shipments/16016920  |
         * @summary Get Details of Specific Shipment
         * @param {string} contentType 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ExternalShipmentsGet(contentType: string, options?: any): AxiosPromise<InlineResponse20017> {
            return ShipmentsApiFp(configuration).v1ExternalShipmentsGet(contentType, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ShipmentsApi - interface
 * @export
 * @interface ShipmentsApi
 */
export interface ShipmentsApiInterface {
    /**
     * Use this API to cancel a created shipment before the \"Out for Pickup\" state. Multiple AWBs can be passed together as an array to cancel them simultaneously.  **Limit: 2000 AWBs**  #### Parameters:  | **PARAMS** | **REQUIRED** | **DATA TYPE** | **DESCRIPTION** | **EXAMPLE** | | --- | --- | --- | --- | --- | | `awbs` | YES | *string* | The AWB/List of AWBs that need to be canceled. | 19041211125783 |
     * @summary Cancel a Shipment
     * @param {string} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShipmentsApiInterface
     */
    v1ExternalOrdersCancelShipmentAwbsPost(body?: string, options?: any): AxiosPromise<InlineResponse2003>;

    /**
     * Get the details of a specific Shipment by passing the value of shipment_id in the endpoint URL. No other body parameters are required.  #### Path:  |          **EXAMPLE**          | |:----------------------------: | |  https://apiv2.shiprocket.in/v1/external/shipments/16016920  |
     * @summary Get Details of Specific Shipment
     * @param {string} contentType 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShipmentsApiInterface
     */
    v1ExternalShipmentsGet(contentType: string, options?: any): AxiosPromise<InlineResponse20017>;

}

/**
 * ShipmentsApi - object-oriented interface
 * @export
 * @class ShipmentsApi
 * @extends {BaseAPI}
 */
export class ShipmentsApi extends BaseAPI implements ShipmentsApiInterface {
    /**
     * Use this API to cancel a created shipment before the \"Out for Pickup\" state. Multiple AWBs can be passed together as an array to cancel them simultaneously.  **Limit: 2000 AWBs**  #### Parameters:  | **PARAMS** | **REQUIRED** | **DATA TYPE** | **DESCRIPTION** | **EXAMPLE** | | --- | --- | --- | --- | --- | | `awbs` | YES | *string* | The AWB/List of AWBs that need to be canceled. | 19041211125783 |
     * @summary Cancel a Shipment
     * @param {string} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShipmentsApi
     */
    public v1ExternalOrdersCancelShipmentAwbsPost(body?: string, options?: any) {
        return ShipmentsApiFp(this.configuration).v1ExternalOrdersCancelShipmentAwbsPost(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get the details of a specific Shipment by passing the value of shipment_id in the endpoint URL. No other body parameters are required.  #### Path:  |          **EXAMPLE**          | |:----------------------------: | |  https://apiv2.shiprocket.in/v1/external/shipments/16016920  |
     * @summary Get Details of Specific Shipment
     * @param {string} contentType 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShipmentsApi
     */
    public v1ExternalShipmentsGet(contentType: string, options?: any) {
        return ShipmentsApiFp(this.configuration).v1ExternalShipmentsGet(contentType, options).then((request) => request(this.axios, this.basePath));
    }

}
